const IPL_TO_UNLOAD = ["grand_parkour_1", "grand_parkour_2", "grand_parkour_3", "grand_parkour_4", "v_hospital", "rc12b_default", "rc12b_hospitalinterior", "hei_bi_hw1_13_door", "redCarpet", "grand_xmas_loc_parkour", "hei_ch1_06e_mansion_original", "hei_ch1_06f_mansion_original", "hei_ch1_06e_props_original", "hei_ch1_roads_original", "apa_ch2_04_mansion_original", "apa_ch2_04_props_original", "apa_ch2_04_mansion_grass", "hei_ch1_09_mansion_original", "hei_ch1_09_props_original"];
const IPL_TO_LOAD = ["grdlc_int_01_shell", "gr_grdlc_int_01", "gr_grdlc_int_02", "gr_entrance_placement", "gr_grdlc_interior_placement", "gr_grdlc_interior_placement_interior_0_grdlc_int_01_milo_", "gr_grdlc_interior_placement_interior_1_grdlc_int_02_milo_", "gr_case10_bunkerclosed", "gr_case9_bunkerclosed", "gr_case3_bunkerclosed", "gr_case0_bunkerclosed", "gr_case1_bunkerclosed", "gr_case2_bunkerclosed", "gr_case5_bunkerclosed", "gr_case7_bunkerclosed", "gr_case11_bunkerclosed", "gr_case6_bunkerclosed", "gr_case4_bunkerclosed", "bh1_47_joshhse_unburnt", "bh1_47_joshhse_unburnt_lod", "CanyonRvrShallow", "ch1_02_open", "Carwash_with_spinners", "sp1_10_real_interior", "sp1_10_real_interior_lod", "ferris_finale_Anim", "fiblobby", "fiblobby_lod", "apa_ss1_11_interior_v_rockclub_milo_", "hei_sm_16_interior_v_bahama_milo_", "hei_hw1_blimp_interior_v_comedy_milo_", "coronertrash", "Coroner_Int_On", "hei_dlc_windows_casino", "hei_dlc_casino_aircon", "hei_ch1_06e_mansion_shared", "hei_ch1_06f_mansion_shared", "hei_ch1_06e_mansion_generic", "hei_ch1_roads_mansion", "hei_ch1_06e_mansion_railings_m", "hei_ch1_06e_mansion_firepit", "m25_2_mansion_gym", "m25_2_dog_house", "apa_ch2_04_mansion_shared", "apa_ch2_04_mansion_generic", "apa_ch2_04_mansion_railings_m", "apa_ch2_04_mansion_furniture", "apa_ch2_04_mansion_firepit", "m25_2_east_mansion_gym", "m25_2_east_dog_house", "hei_ch1_09_mansion_shared", "hei_ch1_09_mansion_generic", "hei_ch1_09_mansion_furniture", "hei_ch1_09_mansion_firepit", "m25_2_tongva_mansion_gym", "m25_2_tongva_dog_house", "shr_int", "facelobby", "CS1_02_cf_onmission1", "CS1_02_cf_onmission2", "CS1_02_cf_onmission3", "CS1_02_cf_onmission4", "CS3_05_water_grp1", "CS3_05_water_grp2", "canyonriver01", "canyonriver01_lod", "railing_start", "farm", "farmint", "farm_lod", "farm_props", "des_farmhouse", "FIBlobby"];
RequestIpl("TrevorsTrailerTrash");
RequestIpl("shr_int");
RequestIpl("post_hiest_unload");
RequestIpl("refit_unload");
RequestIpl("id2_14_during_door");
RequestIpl("id2_14_during1");
RequestIpl("sp1_10_real_interior");
RequestIpl("sp1_10_real_interior_lod");
RequestIpl("ch1_02_open");
RequestIpl("bkr_bi_id1_23_door");
RequestIpl("lr_cs6_08_grave_closed");
RequestIpl("bkr_bi_hw1_13_int");
RequestIpl("CanyonRvrShallow");
RequestIpl("bh1_47_joshhse_unburnt");
RequestIpl("bh1_47_joshhse_unburnt_lod");
RequestIpl("hei_carrier");
RequestIpl("hei_carrier_distantlights");
RequestIpl("hei_Carrier_int1");
RequestIpl("hei_Carrier_int2");
RequestIpl("hei_Carrier_int3");
RequestIpl("hei_Carrier_int4");
RequestIpl("hei_Carrier_int5");
RequestIpl("hei_Carrier_int6");
RequestIpl("hei_carrier_lodlights");
RequestIpl("hei_carrier_slod");
RequestIpl("hei_yacht_heist");
RequestIpl("hei_yacht_heist_Bar");
RequestIpl("hei_yacht_heist_Bedrm");
RequestIpl("hei_yacht_heist_Bridge");
RequestIpl("hei_yacht_heist_DistantLights");
RequestIpl("hei_yacht_heist_enginrm");
RequestIpl("hei_yacht_heist_LODLights");
RequestIpl("hei_yacht_heist_Lounge");
RequestIpl("v_tunnel_hole_swap");
IPL_TO_UNLOAD.forEach(_0x4f0bfd => {
  mp.game.streaming.removeIpl(_0x4f0bfd);
});
IPL_TO_LOAD.forEach(_0x51e8c5 => {
  mp.game.streaming.requestIpl(_0x51e8c5);
});