var sounds = [{
  id: 0,
  soundName: "10s",
  soundSetName: "MP_MISSION_COUNTDOWN_SOUNDSET"
}, {
  id: 1,
  soundName: "1st_Person_Transition",
  soundSetName: "PLAYER_SWITCH_CUSTOM_SOUNDSET"
}, {
  id: 2,
  soundName: "3_2_1",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 3,
  soundName: "3_2_1_NON_RACE",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 4,
  soundName: "5_SEC_WARNING",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 5,
  soundName: "5_Second_Timer",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 6,
  soundName: "5s",
  soundSetName: "MP_MISSION_COUNTDOWN_SOUNDSET"
}, {
  id: 7,
  soundName: "5s_To_Event_Start_Countdown",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 8,
  soundName: "Airhorn",
  soundSetName: "DLC_TG_Running_Back_Sounds"
}, {
  id: 9,
  soundName: "Apt_Style_Purchase",
  soundSetName: "DLC_APT_Apartment_SoundSet"
}, {
  id: 10,
  soundName: "ARM_3_CAR_GLASS_CRASH",
  soundSetName: "0"
}, {
  id: 11,
  soundName: "ARM_3_PISTOL_COCK",
  soundSetName: "0"
}, {
  id: 12,
  soundName: "ARM_WRESTLING_WHOOSH_MASTER",
  soundSetName: "0"
}, {
  id: 13,
  soundName: "Arming_Countdown",
  soundSetName: "GTAO_Speed_Convoy_Soundset"
}, {
  id: 14,
  soundName: "ASSASSINATIONS_HOTEL_TIMER_COUNTDOWN",
  soundSetName: "ASSASSINATION_MULTI"
}, {
  id: 15,
  soundName: "ATM_WINDOW",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 16,
  soundName: "BACK",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 17,
  soundName: "BACK",
  soundSetName: "HUD_FREEMODE_SOUNDSET"
}, {
  id: 18,
  soundName: "BACK",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 20,
  soundName: "BACK",
  soundSetName: "HUD_FRONTEND_MP_SOUNDSET"
}, {
  id: 21,
  soundName: "BACK",
  soundSetName: "HUD_FRONTEND_TATTOO_SHOP_SOUNDSET"
}, {
  id: 22,
  soundName: "BACK",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 23,
  soundName: "Banshee2_Upgrade",
  soundSetName: "JA16_Super_Mod_Garage_Sounds"
}, {
  id: 24,
  soundName: "BASE_JUMP_PASSED",
  soundSetName: "HUD_AWARDS"
}, {
  id: 25,
  soundName: "Beast_Checkpoint",
  soundSetName: "APT_BvS_Soundset"
}, {
  id: 26,
  soundName: "Beast_Checkpoint_NPC",
  soundSetName: "APT_BvS_Soundset"
}, {
  id: 27,
  soundName: "Bed",
  soundSetName: "WastedSounds"
}, {
  id: 28,
  soundName: "Beep_Green",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 29,
  soundName: "Beep_Red",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 30,
  soundName: "Blade_Appear",
  soundSetName: "APT_BvS_Soundset"
}, {
  id: 31,
  soundName: "BOATS_PLANES_HELIS_BOOM",
  soundSetName: "MP_LOBBY_SOUNDS"
}, {
  id: 32,
  soundName: "Bomb_Disarmed",
  soundSetName: "GTAO_Speed_Convoy_Soundset"
}, {
  id: 33,
  soundName: "Boss_Blipped",
  soundSetName: "GTAO_Magnate_Hunt_Boss_SoundSet"
}, {
  id: 34,
  soundName: "Boss_Message_Orange",
  soundSetName: "GTAO_Boss_Goons_FM_Soundset"
}, {
  id: 35,
  soundName: "Breaker_01",
  soundSetName: "DLC_HALLOWEEN_FVJ_Sounds"
}, {
  id: 36,
  soundName: "Breaker_02",
  soundSetName: "DLC_HALLOWEEN_FVJ_Sounds"
}, {
  id: 37,
  soundName: "BULL_SHARK_TESTOSTERONE_END_MASTER",
  soundSetName: ""
}, {
  id: 38,
  soundName: "BULL_SHARK_TESTOSTERONE_START_MASTER",
  soundSetName: ""
}, {
  id: 39,
  soundName: "Bus_Schedule_Pickup",
  soundSetName: "DLC_PRISON_BREAK_HEIST_SOUNDS"
}, {
  id: 40,
  soundName: "CABLE_SNAPS",
  soundSetName: "CONSTRUCTION_ACCIDENT_1_SOUNDS"
}, {
  id: 41,
  soundName: "CAM_PAN_DARTS",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 42,
  soundName: "Camera_Shoot",
  soundSetName: "Phone_Soundset_Franklin"
}, {
  id: 43,
  soundName: "CANCEL",
  soundSetName: "HUD_FREEMODE_SOUNDSET"
}, {
  id: 44,
  soundName: "CANCEL",
  soundSetName: "HUD_FRONTEND_CLOTHESSHOP_SOUNDSET"
}, {
  id: 45,
  soundName: "CANCEL",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 46,
  soundName: "CANCEL",
  soundSetName: "HUD_LIQUOR_STORE_SOUNDSET"
}, {
  id: 47,
  soundName: "CANCEL",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 48,
  soundName: "CAR_BIKE_WHOOSH",
  soundSetName: "MP_LOBBY_SOUNDS"
}, {
  id: 49,
  soundName: "CHALLENGE_UNLOCKED",
  soundSetName: "HUD_AWARDS"
}, {
  id: 50,
  soundName: "CHARACTER_SELECT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 51,
  soundName: "CHECKPOINT_AHEAD",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 52,
  soundName: "Checkpoint_Beast_Hit",
  soundSetName: "FM_Events_Sasquatch_Sounds"
}, {
  id: 53,
  soundName: "CHECKPOINT_BEHIND",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 54,
  soundName: "Checkpoint_Cash_Hit",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 55,
  soundName: "Checkpoint_Hit",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 56,
  soundName: "CHECKPOINT_MISSED",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 57,
  soundName: "CHECKPOINT_NORMAL",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 58,
  soundName: "CHECKPOINT_PERFECT",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 59,
  soundName: "Checkpoint_Teammate",
  soundSetName: "GTAO_Shepherd_Sounds"
}, {
  id: 60,
  soundName: "CHECKPOINT_UNDER_THE_BRIDGE",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 61,
  soundName: "Cheers",
  soundSetName: "DLC_TG_Running_Back_Sounds"
}, {
  id: 62,
  soundName: "Click",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 63,
  soundName: "CLICK_BACK",
  soundSetName: "WEB_NAVIGATION_SOUNDS_PHONE"
}, {
  id: 64,
  soundName: "Click_Fail",
  soundSetName: "WEB_NAVIGATION_SOUNDS_PHONE"
}, {
  id: 65,
  soundName: "Click_Special",
  soundSetName: "WEB_NAVIGATION_SOUNDS_PHONE"
}, {
  id: 66,
  soundName: "CLOSE_WINDOW",
  soundSetName: "LESTER1A_SOUNDS"
}, {
  id: 67,
  soundName: "CLOSED",
  soundSetName: "DLC_APT_YACHT_DOOR_SOUNDS"
}, {
  id: 68,
  soundName: "CLOSED",
  soundSetName: "MP_PROPERTIES_ELEVATOR_DOORS"
}, {
  id: 69,
  soundName: "COMPUTERS_MOUSE_CLICK",
  soundSetName: "0"
}, {
  id: 70,
  soundName: "CONFIRM_BEEP",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 71,
  soundName: "CONTINUE",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 72,
  soundName: "Continue_Accepted",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 73,
  soundName: "Continue_Appears",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 74,
  soundName: "Crash",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 75,
  soundName: "Criminal_Damage_High_Value",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 76,
  soundName: "Criminal_Damage_Kill_Player",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 77,
  soundName: "Criminal_Damage_Low_Value",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 78,
  soundName: "CUTSCENE_DIALOGUE_OVERRIDE_SOUND_01",
  soundSetName: "0"
}, {
  id: 79,
  soundName: "CUTSCENE_DIALOGUE_OVERRIDE_SOUND_02",
  soundSetName: "0"
}, {
  id: 80,
  soundName: "Cycle_Item",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 81,
  soundName: "DELETE",
  soundSetName: "HUD_DEATHMATCH_SOUNDSET"
}, {
  id: 82,
  soundName: "Delete_Placed_Prop",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 83,
  soundName: "Deliver_Pick_Up",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 84,
  soundName: "DiggerRevOneShot",
  soundSetName: "BulldozerDefault"
}, {
  id: 85,
  soundName: "Door_Open",
  soundSetName: "DOCKS_HEIST_FINALE_2B_SOUNDS"
}, {
  id: 86,
  soundName: "Drill_Pin_Break",
  soundSetName: "DLC_HEIST_FLEECA_SOUNDSET"
}, {
  id: 87,
  soundName: "Dropped",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 88,
  soundName: "DRUG_TRAFFIC_AIR_BOMB_DROP_ERROR_MASTER",
  soundSetName: "0"
}, {
  id: 89,
  soundName: "DRUG_TRAFFIC_AIR_SCREAMS",
  soundSetName: "0"
}, {
  id: 90,
  soundName: "EDIT",
  soundSetName: "HUD_DEATHMATCH_SOUNDSET"
}, {
  id: 91,
  soundName: "End_Squelch",
  soundSetName: "CB_RADIO_SFX"
}, {
  id: 92,
  soundName: "Enemy_Capture_Start",
  soundSetName: "GTAO_Magnate_Yacht_Attack_Soundset"
}, {
  id: 93,
  soundName: "Enemy_Deliver",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 94,
  soundName: "Enemy_Pick_Up",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 95,
  soundName: "Enter_1st",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 96,
  soundName: "Enter_1st",
  soundSetName: "GTAO_Magnate_Boss_Modes_Soundset"
}, {
  id: 97,
  soundName: "Enter_Area",
  soundSetName: "DLC_Lowrider_Relay_Race_Sounds"
}, {
  id: 98,
  soundName: "Enter_Capture_Zone",
  soundSetName: "DLC_Apartments_Drop_Zone_Sounds"
}, {
  id: 99,
  soundName: "ERROR",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 100,
  soundName: "ERROR",
  soundSetName: "HUD_FRONTEND_CLOTHESSHOP_SOUNDSET"
}, {
  id: 101,
  soundName: "ERROR",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 102,
  soundName: "ERROR",
  soundSetName: "HUD_FRONTEND_TATTOO_SHOP_SOUNDSET"
}, {
  id: 103,
  soundName: "ERROR",
  soundSetName: "HUD_LIQUOR_STORE_SOUNDSET"
}, {
  id: 104,
  soundName: "Event_Message_Purple",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 105,
  soundName: "Event_Start_Text",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 106,
  soundName: "EXILE_3_TRAIN_BRAKE_PULL_MASTER",
  soundSetName: "0"
}, {
  id: 107,
  soundName: "EXILE_3_TRAIN_BRAKE_RELEASE_MASTER",
  soundSetName: "0"
}, {
  id: 108,
  soundName: "EXIT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 109,
  soundName: "Exit_Capture_Zone",
  soundSetName: "DLC_Apartments_Drop_Zone_Sounds"
}, {
  id: 110,
  soundName: "Failure",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 111,
  soundName: "Falling_Crates",
  soundSetName: "EXILE1"
}, {
  id: 112,
  soundName: "FAMILY_1_CAR_BREAKDOWN",
  soundSetName: "FAMILY1_BOAT"
}, {
  id: 113,
  soundName: "FAMILY_1_CAR_BREAKDOWN_ADDITIONAL",
  soundSetName: "FAMILY1_BOAT"
}, {
  id: 114,
  soundName: "Faster_Bar_Full",
  soundSetName: "RESPAWN_ONLINE_SOUNDSET"
}, {
  id: 115,
  soundName: "Faster_Click",
  soundSetName: "RESPAWN_ONLINE_SOUNDSET"
}, {
  id: 116,
  soundName: "FestiveGift",
  soundSetName: "Feed_Message_Sounds"
}, {
  id: 117,
  soundName: "FIRST_PLACE",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 118,
  soundName: "FLIGHT_SCHOOL_LESSON_PASSED",
  soundSetName: "HUD_AWARDS"
}, {
  id: 119,
  soundName: "FLYING_STREAM_END_INSTANT",
  soundSetName: "FAMILY_5_SOUNDS"
}, {
  id: 120,
  soundName: "FocusIn",
  soundSetName: "HintCamSounds"
}, {
  id: 121,
  soundName: "FocusOut",
  soundSetName: "HintCamSounds"
}, {
  id: 122,
  soundName: "Friend_Deliver",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 123,
  soundName: "Friend_Pick_Up",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 124,
  soundName: "Friend_Pick_Up",
  soundSetName: "HUD_FRONTEND_MP_COLLECTABLE_SOUNDS"
}, {
  id: 125,
  soundName: "Frontend_Beast_Fade_Screen",
  soundSetName: "FM_Events_Sasquatch_Sounds"
}, {
  id: 126,
  soundName: "Frontend_Beast_Freeze_Screen",
  soundSetName: "FM_Events_Sasquatch_Sounds"
}, {
  id: 127,
  soundName: "Frontend_Beast_Text_Hit",
  soundSetName: "FM_Events_Sasquatch_Sounds"
}, {
  id: 128,
  soundName: "Frontend_Beast_Transform_Back",
  soundSetName: "FM_Events_Sasquatch_Sounds"
}, {
  id: 129,
  soundName: "GO",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 130,
  soundName: "GO_NONE_RACE",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 131,
  soundName: "Goal",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 132,
  soundName: "GOLF_BIRDIE",
  soundSetName: "HUD_AWARDS"
}, {
  id: 133,
  soundName: "GOLF_EAGLE",
  soundSetName: "HUD_AWARDS"
}, {
  id: 134,
  soundName: "GOLF_HUD_HOLE_IN_ONE_MASTER",
  soundSetName: "0"
}, {
  id: 135,
  soundName: "GOLF_HUD_SCORECARD_MASTER",
  soundSetName: "0"
}, {
  id: 136,
  soundName: "GOLF_NEW_RECORD",
  soundSetName: "HUD_AWARDS"
}, {
  id: 137,
  soundName: "Goon_Paid_Small",
  soundSetName: "GTAO_Boss_Goons_FM_Soundset"
}, {
  id: 138,
  soundName: "Grab_Parachute",
  soundSetName: "BASEJUMPS_SOUNDS"
}, {
  id: 139,
  soundName: "Hack_Failed",
  soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
  id: 140,
  soundName: "Hack_Success",
  soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
  id: 141,
  soundName: "HACKING_CLICK",
  soundSetName: "0"
}, {
  id: 142,
  soundName: "HACKING_CLICK_BAD",
  soundSetName: "0"
}, {
  id: 143,
  soundName: "HACKING_CLICK_GOOD",
  soundSetName: "0"
}, {
  id: 144,
  soundName: "HACKING_FAILURE",
  soundSetName: "0"
}, {
  id: 145,
  soundName: "HACKING_MOVE_CURSOR",
  soundSetName: "0"
}, {
  id: 146,
  soundName: "HACKING_SUCCESS",
  soundSetName: "0"
}, {
  id: 147,
  soundName: "Hang_Up",
  soundSetName: "Phone_SoundSet_Michael"
}, {
  id: 148,
  soundName: "HIGHLIGHT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 149,
  soundName: "Highlight_Accept",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 150,
  soundName: "Highlight_Cancel",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 151,
  soundName: "Highlight_Error",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 152,
  soundName: "Highlight_Move",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 153,
  soundName: "HIGHLIGHT_NAV_UP_DOWN",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 154,
  soundName: "Hit",
  soundSetName: "RESPAWN_ONLINE_SOUNDSET"
}, {
  id: 155,
  soundName: "Hit",
  soundSetName: "RESPAWN_SOUNDSET"
}, {
  id: 156,
  soundName: "Hit_1",
  soundSetName: "LONG_PLAYER_SWITCH_SOUNDS"
}, {
  id: 157,
  soundName: "Hit_In",
  soundSetName: "PLAYER_SWITCH_CUSTOM_SOUNDSET"
}, {
  id: 158,
  soundName: "Hit_Out",
  soundSetName: "PLAYER_SWITCH_CUSTOM_SOUNDSET"
}, {
  id: 159,
  soundName: "HOORAY",
  soundSetName: "BARRY_02_SOUNDSET"
}, {
  id: 160,
  soundName: "HORDE_COOL_DOWN_TIMER",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 161,
  soundName: "HUD_FREEMODE_CANCEL_MASTER",
  soundSetName: "0"
}, {
  id: 162,
  soundName: "Kill_List_Counter",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 163,
  soundName: "LAMAR1_PARTYGIRLS_master",
  soundSetName: "0"
}, {
  id: 164,
  soundName: "LEADER_BOARD",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 165,
  soundName: "LEADERBOARD",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 166,
  soundName: "Lester_Laugh_Phone",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 167,
  soundName: "Lights_On",
  soundSetName: "GTAO_MUGSHOT_ROOM_SOUNDS"
}, {
  id: 168,
  soundName: "LIMIT",
  soundSetName: "DLC_APT_YACHT_DOOR_SOUNDS"
}, {
  id: 169,
  soundName: "LIMIT",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS"
}, {
  id: 170,
  soundName: "LIMIT",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS"
}, {
  id: 171,
  soundName: "Load_Scene",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 172,
  soundName: "LOCAL_PLYR_CASH_COUNTER_COMPLETE",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 173,
  soundName: "LOCAL_PLYR_CASH_COUNTER_COMPLETE",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 174,
  soundName: "LOOSE_MATCH",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 175,
  soundName: "Lose_1st",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 176,
  soundName: "Lose_1st",
  soundSetName: "GTAO_Magnate_Boss_Modes_Soundset"
}, {
  id: 177,
  soundName: "LOSER",
  soundSetName: "HUD_AWARDS"
}, {
  id: 178,
  soundName: "Lowrider_Upgrade",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds"
}, {
  id: 179,
  soundName: "Map_Roll_Down",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 180,
  soundName: "Map_Roll_Up",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 181,
  soundName: "MARKER_ERASE",
  soundSetName: "HEIST_BULLETIN_BOARD_SOUNDSET"
}, {
  id: 182,
  soundName: "MARTIN1_DISTANT_TRAIN_HORNS_MASTER",
  soundSetName: "0"
}, {
  id: 183,
  soundName: "MEDAL_BRONZE",
  soundSetName: "HUD_AWARDS"
}, {
  id: 184,
  soundName: "MEDAL_GOLD",
  soundSetName: "HUD_AWARDS"
}, {
  id: 185,
  soundName: "MEDAL_SILVER",
  soundSetName: "HUD_AWARDS"
}, {
  id: 186,
  soundName: "MEDAL_UP",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 187,
  soundName: "Menu_Accept",
  soundSetName: "Phone_SoundSet_Default"
}, {
  id: 188,
  soundName: "MICHAEL_LONG_SCREAM",
  soundSetName: "FAMILY_5_SOUNDS"
}, {
  id: 189,
  soundName: "MICHAEL_SOFA_REMOTE_CLICK_VOLUME_MASTER",
  soundSetName: "0"
}, {
  id: 190,
  soundName: "MICHAEL_SOFA_TV_CHANGE_CHANNEL_MASTER",
  soundSetName: "0"
}, {
  id: 191,
  soundName: "MICHAEL_SOFA_TV_ON_MASTER",
  soundSetName: "0"
}, {
  id: 192,
  soundName: "Mission_Pass_Notify",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 193,
  soundName: "MP_5_SECOND_TIMER",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 194,
  soundName: "MP_AWARD",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 195,
  soundName: "MP_Flash",
  soundSetName: "WastedSounds"
}, {
  id: 196,
  soundName: "MP_IDLE_KICK",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 197,
  soundName: "MP_IDLE_TIMER",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 198,
  soundName: "MP_Impact",
  soundSetName: "WastedSounds"
}, {
  id: 199,
  soundName: "MP_RANK_UP",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 200,
  soundName: "MP_WAVE_COMPLETE",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 201,
  soundName: "NAV",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 202,
  soundName: "Nav_Arrow_Ahead",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 203,
  soundName: "Nav_Arrow_Behind",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 204,
  soundName: "Nav_Arrow_Left",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 205,
  soundName: "Nav_Arrow_Right",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 206,
  soundName: "NAV_LEFT_RIGHT",
  soundSetName: "HUD_FREEMODE_SOUNDSET"
}, {
  id: 207,
  soundName: "NAV_LEFT_RIGHT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 208,
  soundName: "NAV_LEFT_RIGHT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 209,
  soundName: "NAV_UP_DOWN",
  soundSetName: "HUD_FREEMODE_SOUNDSET"
}, {
  id: 210,
  soundName: "NAV_UP_DOWN",
  soundSetName: "HUD_FRONTEND_CLOTHESSHOP_SOUNDSET"
}, {
  id: 211,
  soundName: "NAV_UP_DOWN",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 212,
  soundName: "NAV_UP_DOWN",
  soundSetName: "HUD_FRONTEND_TATTOO_SHOP_SOUNDSET"
}, {
  id: 213,
  soundName: "NAV_UP_DOWN",
  soundSetName: "HUD_LIQUOR_STORE_SOUNDSET"
}, {
  id: 214,
  soundName: "NAV_UP_DOWN",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 215,
  soundName: "Near_Miss_Counter_Reset",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 216,
  soundName: "NET_RACE_START_EVENT_MASTER",
  soundSetName: "0"
}, {
  id: 217,
  soundName: "NO",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 218,
  soundName: "Object_Collect_Player",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 219,
  soundName: "Object_Collect_Remote",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 220,
  soundName: "Object_Dropped_Remote",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 221,
  soundName: "Off_High",
  soundSetName: "MP_RADIO_SFX"
}, {
  id: 222,
  soundName: "OK",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 223,
  soundName: "ON",
  soundSetName: "NOIR_FILTER_SOUNDS"
}, {
  id: 224,
  soundName: "On_Call_Player_Join",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 225,
  soundName: "Oneshot_Final",
  soundSetName: "MP_MISSION_COUNTDOWN_SOUNDSET"
}, {
  id: 226,
  soundName: "OOB_Cancel",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 227,
  soundName: "OOB_Start",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 228,
  soundName: "OPEN_WINDOW",
  soundSetName: "LESTER1A_SOUNDS"
}, {
  id: 229,
  soundName: "OPENED",
  soundSetName: "MP_PROPERTIES_ELEVATOR_DOORS"
}, {
  id: 230,
  soundName: "OTHER_TEXT",
  soundSetName: "HUD_AWARDS"
}, {
  id: 231,
  soundName: "Out_Of_Area",
  soundSetName: "DLC_Lowrider_Relay_Race_Sounds"
}, {
  id: 232,
  soundName: "Out_Of_Bounds_Timer",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 233,
  soundName: "Paper_Shuffle",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 234,
  soundName: "Parcel_Vehicle_Lost",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 235,
  soundName: "Payment_Non_Player",
  soundSetName: "DLC_HEISTS_GENERIC_SOUNDS"
}, {
  id: 236,
  soundName: "Payment_Player",
  soundSetName: "DLC_HEISTS_GENERIC_SOUNDS"
}, {
  id: 237,
  soundName: "Pen_Tick",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 238,
  soundName: "PERSON_SCROLL",
  soundSetName: "HEIST_BULLETIN_BOARD_SOUNDSET"
}, {
  id: 239,
  soundName: "PERSON_SELECT",
  soundSetName: "HEIST_BULLETIN_BOARD_SOUNDSET"
}, {
  id: 240,
  soundName: "Phone_Generic_Key_02",
  soundSetName: "HUD_MINIGAME_SOUNDSET"
}, {
  id: 241,
  soundName: "Phone_Generic_Key_03",
  soundSetName: "HUD_MINIGAME_SOUNDSET"
}, {
  id: 242,
  soundName: "PICK_UP",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 243,
  soundName: "PICK_UP_WEAPON",
  soundSetName: "HUD_FRONTEND_CUSTOM_SOUNDSET"
}, {
  id: 244,
  soundName: "PICK_UP_SOUND",
  soundSetName: "HUD_FRONTEND_CUSTOM_SOUNDSET"
}, {
  id: 245,
  soundName: "PICKUP_WEAPON_SMOKEGRENADE",
  soundSetName: "HUD_FRONTEND_WEAPONS_PICKUPS_SOUNDSET"
}, {
  id: 246,
  soundName: "Pin_Bad",
  soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
  id: 247,
  soundName: "PIN_BUTTON",
  soundSetName: "ATM_SOUNDS"
}, {
  id: 248,
  soundName: "Pin_Centred",
  soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
  id: 249,
  soundName: "Pin_Good",
  soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
  id: 250,
  soundName: "PIPES_LAND",
  soundSetName: "CONSTRUCTION_ACCIDENT_1_SOUNDS"
}, {
  id: 251,
  soundName: "Place_Prop_Fail",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 252,
  soundName: "Place_Prop_Success",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 253,
  soundName: "Player_Collect",
  soundSetName: "DLC_PILOT_MP_HUD_SOUNDS"
}, {
  id: 254,
  soundName: "Player_Enter_Line",
  soundSetName: "GTAO_FM_Cross_The_Line_Soundset"
}, {
  id: 255,
  soundName: "Player_Exit_Line",
  soundSetName: "GTAO_FM_Cross_The_Line_Soundset"
}, {
  id: 256,
  soundName: "Power_Down",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 257,
  soundName: "Pre_Screen_Stinger",
  soundSetName: "DLC_HEISTS_FAILED_SCREEN_SOUNDS"
}, {
  id: 258,
  soundName: "Pre_Screen_Stinger",
  soundSetName: "DLC_HEISTS_FINALE_SCREEN_SOUNDS"
}, {
  id: 259,
  soundName: "Pre_Screen_Stinger",
  soundSetName: "DLC_HEISTS_PREP_SCREEN_SOUNDS"
}, {
  id: 260,
  soundName: "PROPERTY_PURCHASE",
  soundSetName: "HUD_AWARDS"
}, {
  id: 261,
  soundName: "PROPERTY_PURCHASE_MEDIUM",
  soundSetName: "HUD_PROPERTY_SOUNDSET"
}, {
  id: 262,
  soundName: "PS2A_DISTANT_TRAIN_HORNS_MASTER",
  soundSetName: "0"
}, {
  id: 263,
  soundName: "PS2A_MONEY_LOST",
  soundSetName: "PALETO_SCORE_2A_BANK_SS"
}, {
  id: 264,
  soundName: "PURCHASE",
  soundSetName: "HUD_FRONTEND_TATTOO_SHOP_SOUNDSET"
}, {
  id: 265,
  soundName: "PURCHASE",
  soundSetName: "HUD_LIQUOR_STORE_SOUNDSET"
}, {
  id: 266,
  soundName: "PUSH",
  soundSetName: "DLC_APT_YACHT_DOOR_SOUNDS"
}, {
  id: 267,
  soundName: "PUSH",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS"
}, {
  id: 268,
  soundName: "PUSH",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS"
}, {
  id: 269,
  soundName: "Put_Away",
  soundSetName: "Phone_SoundSet_Michael"
}, {
  id: 270,
  soundName: "QUIT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 271,
  soundName: "QUIT_WHOOSH",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 272,
  soundName: "RACE_PLACED",
  soundSetName: "HUD_AWARDS"
}, {
  id: 273,
  soundName: "Radar_Beast_Blip",
  soundSetName: "FM_Events_Sasquatch_Sounds"
}, {
  id: 274,
  soundName: "RAMP_DOWN",
  soundSetName: "TRUCK_RAMP_DOWN"
}, {
  id: 275,
  soundName: "RAMP_UP",
  soundSetName: "TRUCK_RAMP_DOWN"
}, {
  id: 276,
  soundName: "RAMPAGE_KILLED_COUNTER_MASTER",
  soundSetName: "0"
}, {
  id: 277,
  soundName: "RAMPAGE_KILLED_HEAD_SHOT_MASTER",
  soundSetName: "0"
}, {
  id: 278,
  soundName: "RAMPAGE_PASSED_MASTER",
  soundSetName: "0"
}, {
  id: 279,
  soundName: "RAMPAGE_ROAR_MASTER",
  soundSetName: "0"
}, {
  id: 280,
  soundName: "RANK_UP",
  soundSetName: "HUD_AWARDS"
}, {
  id: 281,
  soundName: "REMOTE_PLYR_CASH_COUNTER_COMPLETE",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 282,
  soundName: "REMOTE_PLYR_CASH_COUNTER_INCREASE",
  soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
  id: 283,
  soundName: "Remote_Sniper_Rifle_Fire",
  soundSetName: "0"
}, {
  id: 284,
  soundName: "Reset_Prop_Position",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 285,
  soundName: "RESTART",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 286,
  soundName: "RETRY",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 287,
  soundName: "Retune_High",
  soundSetName: "MP_RADIO_SFX"
}, {
  id: 288,
  soundName: "ROBBERY_MONEY_TOTAL",
  soundSetName: "HUD_FRONTEND_CUSTOM_SOUNDSET"
}, {
  id: 289,
  soundName: "ROPE_CUT",
  soundSetName: "ROPE_CUT_SOUNDSET"
}, {
  id: 290,
  soundName: "ROUND_ENDING_STINGER_CUSTOM",
  soundSetName: "CELEBRATION_SOUNDSET"
}, {
  id: 291,
  soundName: "Save_Scene",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 292,
  soundName: "SCOPE_UI_MASTER",
  soundSetName: "0"
}, {
  id: 293,
  soundName: "SCREEN_FLASH",
  soundSetName: "CELEBRATION_SOUNDSET"
}, {
  id: 294,
  soundName: "ScreenFlash",
  soundSetName: "MissionFailedSounds"
}, {
  id: 295,
  soundName: "ScreenFlash",
  soundSetName: "WastedSounds"
}, {
  id: 296,
  soundName: "SCREEN_SWIPE",
  soundSetName: "CELEBRATION_SWIPE"
}, {
  id: 297,
  soundName: "SELECT",
  soundSetName: "HUD_FREEMODE_SOUNDSET"
}, {
  id: 298,
  soundName: "SELECT",
  soundSetName: "HUD_FRONTEND_CLOTHESSHOP_SOUNDSET"
}, {
  id: 299,
  soundName: "SELECT",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 300,
  soundName: "SELECT",
  soundSetName: "HUD_FRONTEND_MP_SOUNDSET"
}, {
  id: 301,
  soundName: "SELECT",
  soundSetName: "HUD_FRONTEND_TATTOO_SHOP_SOUNDSET"
}, {
  id: 302,
  soundName: "SELECT",
  soundSetName: "HUD_LIQUOR_STORE_SOUNDSET"
}, {
  id: 303,
  soundName: "SELECT",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 304,
  soundName: "Select_Placed_Prop",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds"
}, {
  id: 305,
  soundName: "Shard_Disappear",
  soundSetName: "GTAO_Boss_Goons_FM_Shard_Sounds"
}, {
  id: 306,
  soundName: "Shard_Disappear",
  soundSetName: "GTAO_FM_Events_Soundset"
}, {
  id: 307,
  soundName: "SHOOTING_RANGE_ROUND_OVER",
  soundSetName: "HUD_AWARDS"
}, {
  id: 308,
  soundName: "Short_Transition_In",
  soundSetName: "PLAYER_SWITCH_CUSTOM_SOUNDSET"
}, {
  id: 309,
  soundName: "Short_Transition_Out",
  soundSetName: "PLAYER_SWITCH_CUSTOM_SOUNDSET"
}, {
  id: 310,
  soundName: "SKIP",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 311,
  soundName: "Start",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 312,
  soundName: "Start_Squelch",
  soundSetName: "CB_RADIO_SFX"
}, {
  id: 313,
  soundName: "STUN_COLLECT",
  soundSetName: "MINUTE_MAN_01_SOUNDSET"
}, {
  id: 314,
  soundName: "Success",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 315,
  soundName: "SultanRS_Upgrade",
  soundSetName: "JA16_Super_Mod_Garage_Sounds"
}, {
  id: 316,
  soundName: "Swap_Sides",
  soundSetName: "DLC_HALLOWEEN_FVJ_Sounds"
}, {
  id: 317,
  soundName: "SWING_SHUT",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS"
}, {
  id: 318,
  soundName: "SWING_SHUT",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS"
}, {
  id: 319,
  soundName: "Tattooing_Oneshot",
  soundSetName: "TATTOOIST_SOUNDS"
}, {
  id: 320,
  soundName: "Tattooing_Oneshot_Remove",
  soundSetName: "TATTOOIST_SOUNDS"
}, {
  id: 321,
  soundName: "Team_Capture_Start",
  soundSetName: "GTAO_Magnate_Yacht_Attack_Soundset"
}, {
  id: 322,
  soundName: "TENNIS_MATCH_POINT",
  soundSetName: "HUD_AWARDS"
}, {
  id: 323,
  soundName: "TENNIS_MATCH_WON",
  soundSetName: "HUD_AWARDS"
}, {
  id: 324,
  soundName: "TextHit",
  soundSetName: "WastedSounds"
}, {
  id: 325,
  soundName: "Thermal_Off",
  soundSetName: "CAR_STEAL_2_SOUNDSET"
}, {
  id: 326,
  soundName: "Thermal_On",
  soundSetName: "CAR_STEAL_2_SOUNDSET"
}, {
  id: 327,
  soundName: "THERMAL_VISION_GOGGLES_OFF_MASTER",
  soundSetName: "0"
}, {
  id: 328,
  soundName: "THERMAL_VISION_GOGGLES_OFF_MASTER",
  soundSetName: "0"
}, {
  id: 329,
  soundName: "THERMAL_VISION_GOGGLES_ON_MASTER",
  soundSetName: "0"
}, {
  id: 330,
  soundName: "TIME_LAPSE_MASTER",
  soundSetName: "0"
}, {
  id: 331,
  soundName: "TIMER",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 332,
  soundName: "Timer_10s",
  soundSetName: "DLC_HALLOWEEN_FVJ_Sounds"
}, {
  id: 333,
  soundName: "TIMER_STOP",
  soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
  id: 334,
  soundName: "TOGGLE_ON",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 335,
  soundName: "TOGGLE_ON",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 336,
  soundName: "Traffic_Control_Fail",
  soundSetName: "BIG_SCORE_3A_SOUNDS"
}, {
  id: 337,
  soundName: "Traffic_Control_Fail_Blank",
  soundSetName: "BIG_SCORE_3A_SOUNDS"
}, {
  id: 338,
  soundName: "Traffic_Control_Light_Switch_Back",
  soundSetName: "BIG_SCORE_3A_SOUNDS"
}, {
  id: 339,
  soundName: "TRAFFIC_CONTROL_MOVE_CROSSHAIR",
  soundSetName: "BIG_SCORE_3A_SOUNDS"
}, {
  id: 340,
  soundName: "Turn",
  soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
  id: 341,
  soundName: "UNDER_THE_BRIDGE",
  soundSetName: "HUD_AWARDS"
}, {
  id: 342,
  soundName: "UNDER_WATER_COME_UP",
  soundSetName: "0"
}, {
  id: 343,
  soundName: "UNDO",
  soundSetName: "HEIST_BULLETIN_BOARD_SOUNDSET"
}, {
  id: 344,
  soundName: "WAYPOINT_SET",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 345,
  soundName: "WEAKEN",
  soundSetName: "CONSTRUCTION_ACCIDENT_1_SOUNDS"
}, {
  id: 346,
  soundName: "WEAPON_AMMO_PURCHASE",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 347,
  soundName: "WEAPON_ATTACHMENT_EQUIP",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 348,
  soundName: "WEAPON_ATTACHMENT_UNEQUIP",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 349,
  soundName: "WEAPON_PURCHASE",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 350,
  soundName: "WEAPON_SELECT_ARMOR",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 351,
  soundName: "WEAPON_SELECT_BATON",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 352,
  soundName: "WEAPON_SELECT_FUEL_CAN",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 353,
  soundName: "WEAPON_SELECT_GRENADE_LAUNCHER",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 354,
  soundName: "WEAPON_SELECT_HANDGUN",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 355,
  soundName: "WEAPON_SELECT_KNIFE",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 356,
  soundName: "WEAPON_SELECT_OTHER",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 357,
  soundName: "WEAPON_SELECT_PARACHUTE",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 358,
  soundName: "WEAPON_SELECT_RIFLE",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 359,
  soundName: "WEAPON_SELECT_RPG_LAUNCHER",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 360,
  soundName: "WEAPON_SELECT_SHOTGUN",
  soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
  id: 361,
  soundName: "Whistle",
  soundSetName: "DLC_TG_Running_Back_Sounds"
}, {
  id: 362,
  soundName: "Whoosh_1s_L_to_R",
  soundSetName: "MP_LOBBY_SOUNDS"
}, {
  id: 363,
  soundName: "Whoosh_1s_R_to_L",
  soundSetName: "MP_LOBBY_SOUNDS"
}, {
  id: 364,
  soundName: "Win",
  soundSetName: "HUD_AWARDS"
}, {
  id: 365,
  soundName: "WOODEN_DOOR_CLOSED_AT",
  soundSetName: "0"
}, {
  id: 366,
  soundName: "WOODEN_DOOR_CLOSING_AT",
  soundSetName: "0"
}, {
  id: 367,
  soundName: "WOODEN_DOOR_OPEN_HANDLE_AT",
  soundSetName: "0"
}, {
  id: 368,
  soundName: "WOODEN_DOOR_OPEN_NO_HANDLE_AT",
  soundSetName: "0"
}, {
  id: 369,
  soundName: "YES",
  soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
  id: 370,
  soundName: "Zone_Enemy_Capture",
  soundSetName: "DLC_Apartments_Drop_Zone_Sounds"
}, {
  id: 371,
  soundName: "Zone_Neutral",
  soundSetName: "DLC_Apartments_Drop_Zone_Sounds"
}, {
  id: 372,
  soundName: "Zone_Team_Capture",
  soundSetName: "DLC_Apartments_Drop_Zone_Sounds"
}, {
  id: 373,
  soundName: "Zoom_In",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 374,
  soundName: "Zoom_Left",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 375,
  soundName: "Zoom_Out",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 376,
  soundName: "Zoom_Right",
  soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
  id: 377,
  soundName: "ACID_BATH_FALL",
  soundSetName: "MICHAEL_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 378,
  soundName: "Amanda_Pulls_Away",
  soundSetName: "FAMILY_6_SOUNDS",
  type: "fromEntity"
}, {
  id: 379,
  soundName: "Architect_Fall",
  soundSetName: "FBI_HEIST_SOUNDSET",
  type: "fromEntity"
}, {
  id: 380,
  soundName: "ARM_WRESTLING_ARM_IMPACT_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 381,
  soundName: "ARM_WRESTLING_WOOD_CREEK_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 382,
  soundName: "Arrive_Station",
  soundSetName: "CABLE_CAR_SOUNDS",
  type: "fromEntity"
}, {
  id: 383,
  soundName: "Attach_Cargo",
  soundSetName: "DOCKS_HEIST_FINALE_2B_SOUNDS",
  type: "fromEntity"
}, {
  id: 384,
  soundName: "Attach_Container",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 385,
  soundName: "Bar_Cut",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 386,
  soundName: "BAR_DELIVER_BOOZE_RATTLE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 387,
  soundName: "Bar_Lower_And_Lock",
  soundSetName: "DLC_IND_ROLLERCOASTER_SOUNDS",
  type: "fromEntity"
}, {
  id: 388,
  soundName: "Bar_Unlock_And_Raise",
  soundSetName: "DLC_IND_ROLLERCOASTER_SOUNDS",
  type: "fromEntity"
}, {
  id: 389,
  soundName: "Beast_Cloak",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 390,
  soundName: "Beast_Die",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 391,
  soundName: "Beast_Jump",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 392,
  soundName: "Beast_Jump_Land",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 393,
  soundName: "Beast_Uncloak",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 394,
  soundName: "Bell",
  soundSetName: "LIFT_NORMAL_SOUNDSET",
  type: "fromEntity"
}, {
  id: 395,
  soundName: "BIG_STOP",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 396,
  soundName: "Bike_Bell",
  soundSetName: "ARM_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 397,
  soundName: "BIKER_PROP_GRIND",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 398,
  soundName: "Birds",
  soundSetName: "ARM_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 399,
  soundName: "BLOWOUT",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 400,
  soundName: "BLOWOUT_B",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 401,
  soundName: "BOAT_WAVE_HIT_SCRIPT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 402,
  soundName: "BODY_FALL_DIVE_WATER_MASTER",
  soundSetName: "docks_heist_finale_2a_sounds",
  type: "fromEntity"
}, {
  id: 403,
  soundName: "Bomb_Armed",
  soundSetName: "GTAO_Speed_Convoy_Soundset",
  type: "fromEntity"
}, {
  id: 404,
  soundName: "Boxcar_Door_Limit",
  soundSetName: "FRANKLIN_0_SOUNDS",
  type: "fromEntity"
}, {
  id: 405,
  soundName: "Boxcar_Door_Slide",
  soundSetName: "FRANKLIN_0_SOUNDS",
  type: "fromEntity"
}, {
  id: 406,
  soundName: "BUILDING_SITE_CRASH",
  soundSetName: "PAPARAZZO_02_SOUNDSETS",
  type: "fromEntity"
}, {
  id: 407,
  soundName: "BUS_HORN",
  soundSetName: "CAR_STEAL_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 408,
  soundName: "CAMERA_FOLEY",
  soundSetName: "PAPARAZZO_02_SOUNDSETS",
  type: "fromEntity"
}, {
  id: 409,
  soundName: "CAR_DROP_WRAP",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 410,
  soundName: "Car_Push_Flex",
  soundSetName: "FINALE_C2_SOUNDS",
  type: "fromEntity"
}, {
  id: 411,
  soundName: "CAR_STEAL_1_IGNITIONS",
  soundSetName: "CAR_STEAL_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 412,
  soundName: "CAR_STEAL_3_AGENT_TYRE_BURST",
  soundSetName: "CAR_STEAL_3_AGENT",
  type: "fromEntity"
}, {
  id: 413,
  soundName: "CAR_STEAL_4_BURNOUT",
  soundSetName: "CAR_STEAL_4_SOUNDSET",
  type: "fromEntity"
}, {
  id: 414,
  soundName: "CAR_THEFT_MOVIE_LOT_DROP_SPIKES",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 415,
  soundName: "CAR_THEFT_MOVIE_LOT_EJECT_SEAT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 416,
  soundName: "Chopper_Destroyed",
  soundSetName: "FBI_HEIST_FIGHT_CHOPPER_SOUNDS",
  type: "fromEntity"
}, {
  id: 417,
  soundName: "Chopper_Goes_Down",
  soundSetName: "FBI_HEIST_FIGHT_CHOPPER_SOUNDS",
  type: "fromEntity"
}, {
  id: 418,
  soundName: "CLOTHES_THROWN",
  soundSetName: "RE_DOMESTIC_SOUNDSET",
  type: "fromEntity"
}, {
  id: 419,
  soundName: "COLLAR",
  soundSetName: "NIGEL_1C_SOUNDSET",
  type: "fromEntity"
}, {
  id: 420,
  soundName: "Container_Attach",
  soundSetName: "CONTAINER_LIFTER_SOUNDS",
  type: "fromEntity"
}, {
  id: 421,
  soundName: "container_door",
  soundSetName: "dlc_prison_break_heist_sounds",
  type: "fromEntity"
}, {
  id: 422,
  soundName: "Container_Impact_Land",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 423,
  soundName: "Container_Land",
  soundSetName: "CONTAINER_LIFTER_SOUNDS",
  type: "fromEntity"
}, {
  id: 424,
  soundName: "Container_Release",
  soundSetName: "CONTAINER_LIFTER_SOUNDS",
  type: "fromEntity"
}, {
  id: 425,
  soundName: "COYOTE_BARK_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 426,
  soundName: "COYOTE_CRY_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 427,
  soundName: "CRASH",
  soundSetName: "PAPARAZZO_03A",
  type: "fromEntity"
}, {
  id: 428,
  soundName: "Crate_Collect",
  soundSetName: "MP_CRATE_DROP_SOUNDS",
  type: "fromEntity"
}, {
  id: 429,
  soundName: "Crate_Land",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 430,
  soundName: "DAMAGED_TRUCK_IDLE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 431,
  soundName: "DARTS_THROW_DART_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 432,
  soundName: "Destroy_Cop_Car",
  soundSetName: "JEWEL_HEIST_SOUNDS",
  type: "fromEntity"
}, {
  id: 433,
  soundName: "Detach_Container",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 434,
  soundName: "DOCKS_HEIST_FINALE_2A_SUB_LAND",
  soundSetName: "DOCKS_HEIST_FINALE_2A_SOUNDS",
  type: "fromEntity"
}, {
  id: 435,
  soundName: "DOOR_CLOSE",
  soundSetName: "CABLE_CAR_SOUNDS",
  type: "fromEntity"
}, {
  id: 436,
  soundName: "DOOR_OPEN",
  soundSetName: "CABLE_CAR_SOUNDS",
  type: "fromEntity"
}, {
  id: 437,
  soundName: "Door_Open",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 438,
  soundName: "Door_Shut",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 439,
  soundName: "Drill_Jam",
  soundSetName: "DLC_HEIST_FLEECA_SOUNDSET",
  type: "fromEntity"
}, {
  id: 440,
  soundName: "Drop_Case",
  soundSetName: "JWL_PREP_2A_SOUNDS",
  type: "fromEntity"
}, {
  id: 441,
  soundName: "DROP_ITEMS",
  soundSetName: "JEWEL_HEIST_SOUNDS",
  type: "fromEntity"
}, {
  id: 442,
  soundName: "DROP_STINGER",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 443,
  soundName: "ELK_BREY_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 444,
  soundName: "ELK_PAIN_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 445,
  soundName: "EMP_Vehicle_Hum",
  soundSetName: "DLC_HEIST_BIOLAB_DELIVER_EMP_SOUNDS",
  type: "fromEntity"
}, {
  id: 446,
  soundName: "Engine_fail",
  soundSetName: "DLC_PILOT_ENGINE_FAILURE_SOUNDS",
  type: "fromEntity"
}, {
  id: 447,
  soundName: "Engine_Rev",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 448,
  soundName: "Engine_Revs",
  soundSetName: "DLC_HEISTS_GENERIC_SOUNDS",
  type: "fromEntity"
}, {
  id: 449,
  soundName: "engineexplosion",
  soundSetName: "DLC_PILOT_CITY_LANDING",
  type: "fromEntity"
}, {
  id: 450,
  soundName: "EXILE_3_LAND_ON_TRAIN_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 451,
  soundName: "EXILE_3_TRAIN_FALL_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 452,
  soundName: "EXILE_3_TYRE_CHIRPS_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 453,
  soundName: "Exit_Engine_Blips",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 454,
  soundName: "FAMILY1_BOOM_SWING1",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 455,
  soundName: "FAMILY1_BOX_HIT_FRANKLIN",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 456,
  soundName: "FAMILY1_CAR_CRASH_BIG",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 457,
  soundName: "FAMILY1_DROP_IN_CAR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 458,
  soundName: "FAMILY1_FAKE_RICOCHET",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 459,
  soundName: "FAMILY1_JUMPTOYACHT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 460,
  soundName: "FAMILY1_LAND_ON_BONNET",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 461,
  soundName: "FAMILY1_THROWN_OVERBOARD1",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 462,
  soundName: "FAMILY3_CABLE_STRAIN_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 463,
  soundName: "FAMILY3_COACH_OUT_WINDOW_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 464,
  soundName: "FAMILY3_REAR_END_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 465,
  soundName: "FBI_01_DMW_GARBAGE_LAND",
  soundSetName: "FBI_01_DMW_02_SOUNDS",
  type: "fromEntity"
}, {
  id: 466,
  soundName: "FBI_02_SNATCH_AND_GRAB_HELI_DOWN",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 467,
  soundName: "FBI_HEIST_H2_ARCHITECT_GRAB_CASE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 468,
  soundName: "FBI_HEIST_SETUP_1_Car_Park_Skid_CR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 469,
  soundName: "FBI_HEIST_SETUP_1_Car_Park_tyre_bump_CR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 470,
  soundName: "FBI_HEIST_SETUP_1_Car_Park_tyre_bump_creak_CR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 471,
  soundName: "FBI_HEIST_SETUP_1_Car_Park_tyre_bump_no_skid_CR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 472,
  soundName: "FBI_HEIST_SETUP_1_Car_Park_tyre_bump_scraped_CR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 473,
  soundName: "FIB3A_LAND_FROM_HEIGHT_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 474,
  soundName: "FINALE_C2_DEVIN_INSIDE_TRUNK_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 475,
  soundName: "Flare",
  soundSetName: "DLC_HEISTS_BIOLAB_FINALE_SOUNDS",
  type: "fromEntity"
}, {
  id: 476,
  soundName: "Franklin_Throttle_Blip",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 477,
  soundName: "Garage_Open",
  soundSetName: "CAR_STEAL_2_SOUNDSET",
  type: "fromEntity"
}, {
  id: 478,
  soundName: "Gas_Tanker_Explosion",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 479,
  soundName: "Gold_Vault_Explosions",
  soundSetName: "BIG_SCORE_3B_SOUNDS",
  type: "fromEntity"
}, {
  id: 480,
  soundName: "GOLF_BACK_SWING_HARD_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 481,
  soundName: "GOLF_BALL_CUP_MISS_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 482,
  soundName: "GOLF_BALL_IMPACT_FLAG_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 483,
  soundName: "GOLF_BALL_IMPACT_LEAVES_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 484,
  soundName: "GOLF_BALL_IN_WATER_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 485,
  soundName: "GOLF_FORWARD_SWING_HARD_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 486,
  soundName: "Grate_Release",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 487,
  soundName: "Gunman_Bike_Crash",
  soundSetName: "JEWEL_HEIST_SOUNDS",
  type: "fromEntity"
}, {
  id: 488,
  soundName: "HIGHREV",
  soundSetName: "PAPARAZZO_02_SOUNDSETS",
  type: "fromEntity"
}, {
  id: 489,
  soundName: "Hood_Open",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 490,
  soundName: "Hood_Shut",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 491,
  soundName: "Hydraulics_Down",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 492,
  soundName: "Hydraulics_Up",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 493,
  soundName: "Keycard_Fail",
  soundSetName: "DLC_HEISTS_BIOLAB_FINALE_SOUNDS",
  type: "fromEntity"
}, {
  id: 494,
  soundName: "Keycard_Success",
  soundSetName: "DLC_HEISTS_BIOLAB_FINALE_SOUNDS",
  type: "fromEntity"
}, {
  id: 495,
  soundName: "KISS",
  soundSetName: "ROAD_RACE_SOUNDSET",
  type: "fromEntity"
}, {
  id: 496,
  soundName: "LAMAR1_FAKE_POLICE_SIREN2_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 497,
  soundName: "Lamar_Throttle_Blip",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 498,
  soundName: "Landing_Tone",
  soundSetName: "DLC_PILOT_ENGINE_FAILURE_SOUNDS",
  type: "fromEntity"
}, {
  id: 499,
  soundName: "Leave_Station",
  soundSetName: "CABLE_CAR_SOUNDS",
  type: "fromEntity"
}, {
  id: 500,
  soundName: "Lock_Damage",
  soundSetName: "JWL_PREP_2A_SOUNDS",
  type: "fromEntity"
}, {
  id: 501,
  soundName: "Lock_Destroyed",
  soundSetName: "JWL_PREP_2A_SOUNDS",
  type: "fromEntity"
}, {
  id: 502,
  soundName: "MARTIN_1_PLANE_CRASH_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 503,
  soundName: "MIC4_CAMERA_FLASH_master",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 504,
  soundName: "MIC_2_CHOPPED_UP_JUMPIN_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 505,
  soundName: "MINCER_FALL",
  soundSetName: "MICHAEL_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 506,
  soundName: "Missile_Incoming_Hit",
  soundSetName: "DOCKS_HEIST_FINALE_2B_SOUNDS",
  type: "fromEntity"
}, {
  id: 507,
  soundName: "Missile_Incoming_Miss",
  soundSetName: "DOCKS_HEIST_FINALE_2B_SOUNDS",
  type: "fromEntity"
}, {
  id: 508,
  soundName: "MOD_SHOP_BRAKES_ONESHOT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 509,
  soundName: "MOD_SHOPS_ENTER_ENGINE_BLIP",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 510,
  soundName: "MOD_SHOPS_EXIT_ENGINE_BLIP",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 511,
  soundName: "MOD_SHOPS_UPGRADE_BLIP",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 512,
  soundName: "Moor_Boat_Engine",
  soundSetName: "DLC_Apt_Yacht_Ambient_Soundset",
  type: "fromEntity"
}, {
  id: 513,
  soundName: "Moor_SEASHARK3_Engine",
  soundSetName: "DLC_Apt_Yacht_Ambient_Soundset",
  type: "fromEntity"
}, {
  id: 514,
  soundName: "Moor_SEASHARK_Engine",
  soundSetName: "DLC_Apt_Yacht_Ambient_Soundset",
  type: "fromEntity"
}, {
  id: 515,
  soundName: "MP_APARTMENT_SHOWER_DOOR_OPEN_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 516,
  soundName: "MP_APARTMENT_SHOWER_GET_DRESSED_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 517,
  soundName: "MP_APARTMENT_SHOWER_GET_UNDRESSED_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 518,
  soundName: "Muscle_Jump",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 519,
  soundName: "Muscle_Land",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 520,
  soundName: "PASSPORT",
  soundSetName: "MINUTE_02_SOUNDSET",
  type: "fromEntity"
}, {
  id: 521,
  soundName: "PED_PHONE_DIAL_01",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 522,
  soundName: "PICK_UP_PARACHUTE",
  soundSetName: "HUD_FRONTEND_CUSTOM_SOUNDSET",
  type: "fromEntity"
}, {
  id: 523,
  soundName: "Pierce",
  soundSetName: "FAMILY_6_SOUNDS",
  type: "fromEntity"
}, {
  id: 524,
  soundName: "Pimp_Gunshot",
  soundSetName: "CAR_STEAL_2_SOUNDSET",
  type: "fromEntity"
}, {
  id: 525,
  soundName: "Pimp_Gunshot_Mic",
  soundSetName: "CAR_STEAL_2_SOUNDSET",
  type: "fromEntity"
}, {
  id: 526,
  soundName: "PLAYER_CALLS_ELK_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 527,
  soundName: "POLICE_CRASH",
  soundSetName: "PAPARAZZO_03A",
  type: "fromEntity"
}, {
  id: 528,
  soundName: "PROPERTIES_PLANE_PROMO_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 529,
  soundName: "PS2A_TRACTOR_THRU_CHAIN_LINK_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 530,
  soundName: "Pt2_Fail",
  soundSetName: "exile_1",
  type: "fromEntity"
}, {
  id: 531,
  soundName: "Put_On_Mask",
  soundSetName: "DLC_HEISTS_GENERIC_SOUNDS",
  type: "fromEntity"
}, {
  id: 532,
  soundName: "Radio_Off",
  soundSetName: "TAXI_SOUNDS",
  type: "fromEntity"
}, {
  id: 533,
  soundName: "Radio_On",
  soundSetName: "TAXI_SOUNDS",
  type: "fromEntity"
}, {
  id: 534,
  soundName: "Release_Crate",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 535,
  soundName: "Remote_Control_Close",
  soundSetName: "PI_Menu_Sounds",
  type: "fromEntity"
}, {
  id: 536,
  soundName: "Remote_Control_Fob",
  soundSetName: "PI_Menu_Sounds",
  type: "fromEntity"
}, {
  id: 537,
  soundName: "Remote_Control_Open",
  soundSetName: "PI_Menu_Sounds",
  type: "fromEntity"
}, {
  id: 538,
  soundName: "Remote_Sniper_Rifle_Fire",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 539,
  soundName: "RFL_SINGLESHOT_NPC_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 540,
  soundName: "Ride_Stop",
  soundSetName: "DLC_IND_ROLLERCOASTER_SOUNDS",
  type: "fromEntity"
}, {
  id: 541,
  soundName: "ROPE_CUT",
  soundSetName: "ROPE_CUT_SOUNDSET",
  type: "fromEntity"
}, {
  id: 542,
  soundName: "Scientist_Approaching",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 543,
  soundName: "Seagulls",
  soundSetName: "JEWEL_HEIST_SOUNDS",
  type: "fromEntity"
}, {
  id: 544,
  soundName: "Shoot_box",
  soundSetName: "Paleto_Score_Setup_Sounds",
  type: "fromEntity"
}, {
  id: 545,
  soundName: "SIREN_BLIP",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 546,
  soundName: "Snip_Ponytail",
  soundSetName: "FAMILY_6_SOUNDS",
  type: "fromEntity"
}, {
  id: 547,
  soundName: "SPAWN",
  soundSetName: "BARRY_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 548,
  soundName: "Speech_Bubble",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 549,
  soundName: "SPIKES",
  soundSetName: "MP_RACE_SPIKES_SOUNDSET",
  type: "fromEntity"
}, {
  id: 550,
  soundName: "spikes",
  soundSetName: "CAR_THEFT_DB5_ESCAPE",
  type: "fromEntity"
}, {
  id: 551,
  soundName: "SPL_RPG_NPC_SHOT_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 552,
  soundName: "stop",
  soundSetName: "DLC_PILOT_Shooting_Range_Sounds",
  type: "fromEntity"
}, {
  id: 553,
  soundName: "Sub_Lift",
  soundSetName: "DOCKS_HEIST_FINALE_2B_SOUNDS",
  type: "fromEntity"
}, {
  id: 554,
  soundName: "SUB_SPLASH",
  soundSetName: "DOCKS_HEIST_PREP_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 555,
  soundName: "SUBWAY_TRAIN_HORNS_AIR_HORN",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 556,
  soundName: "SUSPENSION_SCRIPT_FORCE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 557,
  soundName: "SWAP_POSITION",
  soundSetName: "DOCKS_HEIST_FINALE_2B_SOUNDS",
  type: "fromEntity"
}, {
  id: 558,
  soundName: "TAKINGS_TIRES_PEELAWAY_master",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 559,
  soundName: "TARGET_PRACTICE_FLIP_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 560,
  soundName: "TARGET_PRACTICE_STOP_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 561,
  soundName: "TARP",
  soundSetName: "JEWEL_HEIST_SOUNDS",
  type: "fromEntity"
}, {
  id: 562,
  soundName: "Teeth_Initial_Pain",
  soundSetName: "FBI_03_Torture_Sounds",
  type: "fromEntity"
}, {
  id: 563,
  soundName: "TENNIS_FOOT_SQUEAKS_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 564,
  soundName: "TENNIS_NPC_BACKSLICE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 565,
  soundName: "TENNIS_NPC_FOREARM_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 566,
  soundName: "TENNIS_NPC_TOPSPIN_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 567,
  soundName: "TENNIS_PLYR_FOREARM_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 568,
  soundName: "TENNIS_PLYR_SERVE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 569,
  soundName: "TENNIS_PLYR_SMASH_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 570,
  soundName: "Toggle_Lights",
  soundSetName: "PI_Menu_Sounds",
  type: "fromEntity"
}, {
  id: 571,
  soundName: "Tone",
  soundSetName: "LIFT_POSH_SOUNDSET",
  type: "fromEntity"
}, {
  id: 572,
  soundName: "Tow_truck_damage",
  soundSetName: "FBI_04_HEAT_SOUNDS",
  type: "fromEntity"
}, {
  id: 573,
  soundName: "TRAFFIC_GROUND_ENEMY_PICK_UP_WEAPON_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 574,
  soundName: "TRAIN_PICK_UP_IMPACT_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 575,
  soundName: "TRAIN_PICK_UP_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 576,
  soundName: "TRAIN_SWITCH_TRACKS_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 577,
  soundName: "Trash_Bag_Land",
  soundSetName: "DLC_HEIST_SERIES_A_SOUNDS",
  type: "fromEntity"
}, {
  id: 578,
  soundName: "TREVOR_1_LEAD_OUT_CR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 579,
  soundName: "TREVOR_1_TRAILER_IMPACT_MASTER_A",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 580,
  soundName: "TREVOR_1_TRAILER_IMPACT_MASTER_B",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 581,
  soundName: "TREVOR_1_TRAILER_IMPACT_MASTER_C",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 582,
  soundName: "Trevor_2_cargo_bay_open",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 583,
  soundName: "Trevor_2_cargo_drop",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 584,
  soundName: "Trevor_2_chopper_explode",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 585,
  soundName: "TREVOR_2_PLANE_START",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 586,
  soundName: "Trevor_2_van_rev",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 587,
  soundName: "Trevor_4_747_Carsplosion",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 588,
  soundName: "Trevor_4_747_Tanker_Explosion",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 589,
  soundName: "Trevor_4_747_Tanker_Horn",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 590,
  soundName: "TRUCK_HORN",
  soundSetName: "CAR_STEAL_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 591,
  soundName: "Truck_Stop",
  soundSetName: "DOCKS_HEIST_SETUP_SOUNDS",
  type: "fromEntity"
}, {
  id: 592,
  soundName: "Trunk_Open",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 593,
  soundName: "Trunk_Shut",
  soundSetName: "Lowrider_Super_Mod_Garage_Sounds",
  type: "fromEntity"
}, {
  id: 594,
  soundName: "tyre",
  soundSetName: "CAR_THEFT_DB5_ESCAPE",
  type: "fromEntity"
}, {
  id: 595,
  soundName: "UNHITCH_TRAILER",
  soundSetName: "FAM4_UNHITCH_TRAILER",
  type: "fromEntity"
}, {
  id: 596,
  soundName: "unlocked_bleep",
  soundSetName: "HACKING_DOOR_UNLOCK_SOUNDS",
  type: "fromEntity"
}, {
  id: 597,
  soundName: "VEHICLE_WATER_SPLASH_HEAVY_SCRIPT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 598,
  soundName: "Warning_Once",
  soundSetName: "TRAIN_HORN",
  type: "fromEntity"
}, {
  id: 599,
  soundName: "BRUSHES_SPINNING",
  soundSetName: "CARWASH_SOUNDS",
  type: "fromEntity"
}, {
  id: 600,
  soundName: "BRUSHES_MOVE",
  soundSetName: "CARWASH_SOUNDS",
  type: "fromEntity"
}, {
  id: 601,
  soundName: "MIND_CONTROL",
  soundSetName: "BARRY_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 602,
  soundName: "PLAYER_BEAMED_UP",
  soundSetName: "BARRY_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 603,
  soundName: "BRUSHES_HIT_CAR",
  soundSetName: "CARWASH_SOUNDS",
  type: "fromEntity"
}, {
  id: 604,
  soundName: "YOGA_INHALE",
  soundSetName: "FAMILY_5_SOUNDS",
  type: "fromEntity"
}, {
  id: 605,
  soundName: "YOGA_EXHALE",
  soundSetName: "FAMILY_5_SOUNDS",
  type: "fromEntity"
}, {
  id: 606,
  soundName: "YOGA_FAIL",
  soundSetName: "FAMILY_5_SOUNDS",
  type: "fromEntity"
}, {
  id: 607,
  soundName: "Running",
  soundSetName: "CABLE_CAR_SOUNDS",
  type: "fromEntity"
}, {
  id: 608,
  soundName: "Interior_Rain",
  soundSetName: "CABLE_CAR_SOUNDS",
  type: "fromEntity"
}, {
  id: 609,
  soundName: "Scissors",
  soundSetName: "Barber_Sounds",
  type: "fromEntity"
}, {
  id: 610,
  soundName: "FREIGHT_ELEVATOR_02_MOTOR",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 611,
  soundName: "Makeup",
  soundSetName: "Barber_Sounds",
  type: "fromEntity"
}, {
  id: 612,
  soundName: "TARGET_PRACTICE_SLIDE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 613,
  soundName: "DRYER",
  soundSetName: "CARWASH_SOUNDS",
  type: "fromEntity"
}, {
  id: 614,
  soundName: "SPRAY",
  soundSetName: "CARWASH_SOUNDS",
  type: "fromEntity"
}, {
  id: 615,
  soundName: "SPRAY_CAR",
  soundSetName: "CARWASH_SOUNDS",
  type: "fromEntity"
}, {
  id: 616,
  soundName: "GOLF_BALL_ROLL_PUTT_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 617,
  soundName: "Count_Start",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 618,
  soundName: "Count_Stop",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 619,
  soundName: "GTAO_MP_APARTMENT_SHOWER_PLASTIC_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 620,
  soundName: "MP_APARTMENT_SHOWER_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 621,
  soundName: "GARDENING_LEAFBLOWER_ANIM_TRIGGERED",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 622,
  soundName: "GENERATOR",
  soundSetName: "THE_FERRIS_WHALE_SOUNDSET",
  type: "fromEntity"
}, {
  id: 623,
  soundName: "CARRIAGE",
  soundSetName: "THE_FERRIS_WHALE_SOUNDSET",
  type: "fromEntity"
}, {
  id: 624,
  soundName: "SLOW_SQUEAK",
  soundSetName: "THE_FERRIS_WHALE_SOUNDSET",
  type: "fromEntity"
}, {
  id: 625,
  soundName: "RAIL_LOOP",
  soundSetName: "MICHAEL_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 626,
  soundName: "Rail_Loop_Skip_Start",
  soundSetName: "MICHAEL_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 627,
  soundName: "MEAT_SLIDE",
  soundSetName: "MICHAEL_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 628,
  soundName: "Move",
  soundSetName: "LIFT_NORMAL_SOUNDSET",
  type: "fromEntity"
}, {
  id: 629,
  soundName: "Gasmask",
  soundSetName: "FBI_HEIST_RAID",
  type: "fromEntity"
}, {
  id: 630,
  soundName: "Explosion_01",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 631,
  soundName: "Land_01",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 632,
  soundName: "Explosion_02",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 633,
  soundName: "Land_02",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 634,
  soundName: "Explosion_03",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 635,
  soundName: "Land_03",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 636,
  soundName: "Explosion_04",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 637,
  soundName: "Land_04",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 638,
  soundName: "Woosh_01",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 639,
  soundName: "Woosh_02",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 640,
  soundName: "Woosh_03",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 641,
  soundName: "Woosh_04",
  soundSetName: "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS",
  type: "fromEntity"
}, {
  id: 642,
  soundName: "Clamp",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 643,
  soundName: "Strain_No_Container",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 644,
  soundName: "MICHAELS_HOUSE_DAUGHTER_SICK_ONESHOT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 645,
  soundName: "ELECTRO_MAGNET_DRONE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 646,
  soundName: "Prop_Drop_Land",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds",
  type: "fromEntity"
}, {
  id: 647,
  soundName: "Prop_Drop_Water",
  soundSetName: "DLC_Dmod_Prop_Editor_Sounds",
  type: "fromEntity"
}, {
  id: 648,
  soundName: "Drill",
  soundSetName: "DLC_HEIST_FLEECA_SOUNDSET",
  type: "fromEntity"
}, {
  id: 649,
  soundName: "DOM",
  soundSetName: "EXTREME_04_SOUNDSET",
  type: "fromEntity"
}, {
  id: 650,
  soundName: "FBI_05_RAID_FOOT_SWISH",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 651,
  soundName: "COLLECT_IN_BAG",
  soundSetName: "NIGEL_1D_SOUNDSET",
  type: "fromEntity"
}, {
  id: 652,
  soundName: "COLLECT_OUT_BAG",
  soundSetName: "NIGEL_1D_SOUNDSET",
  type: "fromEntity"
}, {
  id: 653,
  soundName: "WHISTLING",
  soundSetName: "NIGEL_1B_SOUNDSET",
  type: "fromEntity"
}, {
  id: 654,
  soundName: "move",
  soundSetName: "DLC_PILOT_Shooting_Range_Sounds",
  type: "fromEntity"
}, {
  id: 655,
  soundName: "IGNITION_FAIL",
  soundSetName: "BARRY_03_SOUNDSET",
  type: "fromEntity"
}, {
  id: 656,
  soundName: "HELI_TURNING_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 657,
  soundName: "MICHAEL_EVENT_AMANDA_REMOVE_HANDCUFFS_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 658,
  soundName: "Move_L_R",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 659,
  soundName: "Attach_Container_Fail",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 660,
  soundName: "CRANE_MOVE_U_D",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 661,
  soundName: "Move_Fail",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 662,
  soundName: "Move_U_D",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 663,
  soundName: "Move_Base",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 664,
  soundName: "Strain",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 665,
  soundName: "TREVOR_1_RAM_TRAILER_REVS",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 666,
  soundName: "Scraping_Ramp",
  soundSetName: "EXTREME_02_SOUNDSET",
  type: "fromEntity"
}, {
  id: 667,
  soundName: "PLAYER_AT_SPEED_FREEFALL_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 668,
  soundName: "TRUNK_THUMPS",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 669,
  soundName: "Plane_Wind",
  soundSetName: "DLC_Pilot_Chase_Parachute_Sounds",
  type: "fromEntity"
}, {
  id: 670,
  soundName: "Ejector_Scream",
  soundSetName: "CAR_STEAL_3_AGENT",
  type: "fromEntity"
}, {
  id: 671,
  soundName: "Warning_Tones",
  soundSetName: "DLC_PILOT_ENGINE_FAILURE_SOUNDS",
  type: "fromEntity"
}, {
  id: 672,
  soundName: "DEVICE",
  soundSetName: "EPSILONISM_04_SOUNDSET",
  type: "fromEntity"
}, {
  id: 673,
  soundName: "IDLE_BEEP",
  soundSetName: "EPSILONISM_04_SOUNDSET",
  type: "fromEntity"
}, {
  id: 674,
  soundName: "CONTINUAL_BEEP",
  soundSetName: "EPSILONISM_04_SOUNDSET",
  type: "fromEntity"
}, {
  id: 675,
  soundName: "SCAN",
  soundSetName: "EPSILONISM_04_SOUNDSET",
  type: "fromEntity"
}, {
  id: 676,
  soundName: "Explosion_Countdown",
  soundSetName: "GTAO_FM_Events_Soundset",
  type: "fromEntity"
}, {
  id: 677,
  soundName: "ALERT",
  soundSetName: "SASQUATCH_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 678,
  soundName: "RUNNING",
  soundSetName: "SASQUATCH_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 679,
  soundName: "WOUNDED",
  soundSetName: "SASQUATCH_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 680,
  soundName: "COUGH",
  soundSetName: "SASQUATCH_01_SOUNDSET",
  type: "fromEntity"
}, {
  id: 681,
  soundName: "TRAIN_COMING",
  soundSetName: "NIGEL_03_SOUNDSET",
  type: "fromEntity"
}, {
  id: 682,
  soundName: "Beast_Attack",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 683,
  soundName: "Beast_Sprint_Loop",
  soundSetName: "APT_BvS_Soundset",
  type: "fromEntity"
}, {
  id: 684,
  soundName: "MIC_1_RAIN_ON_PLANE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 685,
  soundName: "CUTTER",
  soundSetName: "BIG_SCORE_3B_SOUNDS",
  type: "fromEntity"
}, {
  id: 686,
  soundName: "Gold_Cage_Collisions",
  soundSetName: "BIG_SCORE_3B_SOUNDS",
  type: "fromEntity"
}, {
  id: 687,
  soundName: "GOLF_FORWARD_SWING_PERFECT_VB_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 688,
  soundName: "GOLF_FORWARD_SWING_VB_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 689,
  soundName: "EXILE_2_GANG_CAR_FIRE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 690,
  soundName: "Fire_Missile_Loop",
  soundSetName: "EXILE_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 691,
  soundName: "Fire_RPG_On_Foot",
  soundSetName: "EXILE_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 692,
  soundName: "Missile_Warning_Sound",
  soundSetName: "EXILE_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 693,
  soundName: "FBI_02_SNATCH_AND_GRAB_DANGLE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 694,
  soundName: "CROWD_WATCHING",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 695,
  soundName: "Biker_Ring_Tone",
  soundSetName: "TREVOR_2_SOUNDS",
  type: "fromEntity"
}, {
  id: 696,
  soundName: "Insert_Coin",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 697,
  soundName: "10_Seconds",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 698,
  soundName: "FRANKLIN_1_PHOTO_SHOOT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 699,
  soundName: "Transition_Sound",
  soundSetName: "EXILE_1",
  type: "fromEntity"
}, {
  id: 700,
  soundName: "Timer",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 701,
  soundName: "Zoom",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 702,
  soundName: "Zoom_Limit",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 703,
  soundName: "Tattoo",
  soundSetName: "FAMILY_6_SOUNDS",
  type: "fromEntity"
}, {
  id: 704,
  soundName: "Turn",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 705,
  soundName: "Turn_Limit",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 706,
  soundName: "ExitWater",
  soundSetName: "GTAO_Hot_Tub_PED_INSIDE_WATER",
  type: "fromEntity"
}, {
  id: 707,
  soundName: "SPL_RPG_DIST_FLIGHT_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 708,
  soundName: "CAR_WHEELS",
  soundSetName: "FINALE_C2_SOUNDS",
  type: "fromEntity"
}, {
  id: 709,
  soundName: "DISTANT_RACERS",
  soundSetName: "ROAD_RACE_SOUNDSET",
  type: "fromEntity"
}, {
  id: 710,
  soundName: "Security_Door_Bomb_Bleeps",
  soundSetName: "Prologue_Sounds",
  type: "fromEntity"
}, {
  id: 711,
  soundName: "UNZIP",
  soundSetName: "FBI_01_SOUNDS",
  type: "fromEntity"
}, {
  id: 712,
  soundName: "Armed",
  soundSetName: "GTAO_Speed_Race_Sounds",
  type: "fromEntity"
}, {
  id: 713,
  soundName: "Countdown",
  soundSetName: "GTAO_Speed_Race_Sounds",
  type: "fromEntity"
}, {
  id: 714,
  soundName: "Explosion_Timer",
  soundSetName: "DLC_Lowrider_Relay_Race_Sounds",
  type: "fromEntity"
}, {
  id: 715,
  soundName: "DOM_BREATHING",
  soundSetName: "EXTREME_03_SOUNDSET",
  type: "fromEntity"
}, {
  id: 716,
  soundName: "DOOR_BUZZ_ONESHOT_MASTER",
  soundSetName: "GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS",
  type: "fromEntity"
}, {
  id: 717,
  soundName: "TEST_SCREAM_SHORT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 718,
  soundName: "PS2A_WELDTORCH_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 719,
  soundName: "Heart_Breathing",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 720,
  soundName: "Franklin_Whistle_For_Chop",
  soundSetName: "SPEECH_RELATED_SOUNDS",
  type: "fromEntity"
}, {
  id: 721,
  soundName: "CONDUCTORS_PORT_OF_LS_2A_LOOP",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 722,
  soundName: "rebreather",
  soundSetName: "docks_heist_finale_2a_sounds",
  type: "fromEntity"
}, {
  id: 723,
  soundName: "foot_swish",
  soundSetName: "docks_heist_finale_2a_sounds",
  type: "fromEntity"
}, {
  id: 724,
  soundName: "BANK_DOOR_OPEN",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 725,
  soundName: "Gold_Trolley_Roll_Player",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 726,
  soundName: "Gold_Trolley_Roll_NPC",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 727,
  soundName: "Truck_Ramp_Scrape",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 728,
  soundName: "Truck_Ramp_Raise",
  soundSetName: "BIG_SCORE_3A_SOUNDS",
  type: "fromEntity"
}, {
  id: 729,
  soundName: "FRANKLINS_HOUSE_SECURITY_LIGHT_OFF",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 730,
  soundName: "FRANKLINS_HOUSE_SECURITY_LIGHT_ON",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 731,
  soundName: "LOOP_REV",
  soundSetName: "PAPARAZZO_02_SOUNDSETS",
  type: "fromEntity"
}, {
  id: 732,
  soundName: "AMBIENT_SEX",
  soundSetName: "PAPARAZZO_02_SOUNDSETS",
  type: "fromEntity"
}, {
  id: 733,
  soundName: "TOWING_ENGINE_TURNING_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 734,
  soundName: "Idling_Throttle_Blip_Loop",
  soundSetName: "ARM_1_SOUNDSET",
  type: "fromEntity"
}, {
  id: 735,
  soundName: "Answer_Phone",
  soundSetName: "Lester1B_Sounds",
  type: "fromEntity"
}, {
  id: 736,
  soundName: "Remote_Ring",
  soundSetName: "Phone_SoundSet_Michael",
  type: "fromEntity"
}, {
  id: 737,
  soundName: "Torch",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 738,
  soundName: "Foot_Swish",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 739,
  soundName: "LIFT_POSH_MOVE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 740,
  soundName: "Monkey_Scream",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 741,
  soundName: "Cable_Strain",
  soundSetName: "FBI_05_SOUNDS",
  type: "fromEntity"
}, {
  id: 742,
  soundName: "Trevor_4_747_Flying_Car",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 743,
  soundName: "SWING",
  soundSetName: "",
  type: "fromEntity"
}, {
  id: 744,
  soundName: "FAKE_REVS_VEHICLE_02",
  soundSetName: "NIGEL_02_SOUNDSET",
  type: "fromEntity"
}, {
  id: 745,
  soundName: "CAR_STEAL_4_RAMP_SCRAPE",
  soundSetName: "CAR_STEAL_4_SOUNDSET",
  type: "fromEntity"
}, {
  id: 746,
  soundName: "Beast_Calls",
  soundSetName: "FM_Events_Sasquatch_Sounds",
  type: "fromEntity"
}, {
  id: 747,
  soundName: "IDLE_BEEP_NPC",
  soundSetName: "EPSILONISM_04_SOUNDSET",
  type: "fromEntity"
}, {
  id: 748,
  soundName: "PLANE_ON_FIRE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 749,
  soundName: "SOLOMON_1_JET_SHOT_EXPLODE",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 750,
  soundName: "BASEJUMPS_CHOPPER_WIND_WAIT",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 751,
  soundName: "Cage_Rattle",
  soundSetName: "DLC_HEIST_BIOLAB_MONKEYS_SOUNDS",
  type: "fromEntity"
}, {
  id: 752,
  soundName: "General_Chatter",
  soundSetName: "DLC_HEIST_BIOLAB_MONKEYS_SOUNDS",
  type: "fromEntity"
}, {
  id: 753,
  soundName: "Screech",
  soundSetName: "DLC_HEIST_BIOLAB_MONKEYS_SOUNDS",
  type: "fromEntity"
}, {
  id: 754,
  soundName: "Crate_Beeps",
  soundSetName: "MP_CRATE_DROP_SOUNDS",
  type: "fromEntity"
}, {
  id: 755,
  soundName: "Container_Impact",
  soundSetName: "CRANE_SOUNDS",
  type: "fromEntity"
}, {
  id: 756,
  soundName: "Helicopter_Wind",
  soundSetName: "BASEJUMPS_SOUNDS",
  type: "fromEntity"
}, {
  id: 757,
  soundName: "Helicopter_Wind_Idle",
  soundSetName: "BASEJUMPS_SOUNDS",
  type: "fromEntity"
}, {
  id: 758,
  soundName: "PED_INSIDE_WATER",
  soundSetName: "PED_INSIDE_WATER",
  type: "fromEntity"
}, {
  id: 759,
  soundName: "PEYOTE_ATTRACT_SOUNDSET",
  soundSetName: "PEYOTE_ATTRACT_SOUNDSET",
  type: "fromEntity"
}, {
  id: 760,
  soundName: "TENNIS_PLYR_BACKSLICE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 761,
  soundName: "TENNIS_PLYR_LOB_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 762,
  soundName: "TENNIS_PLYR_SMASH_BACKSLICE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 763,
  soundName: "TENNIS_AMB_SERVE_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 764,
  soundName: "TENNIS_AMB_SMASH_MASTER",
  soundSetName: "0",
  type: "fromEntity"
}, {
  id: 765,
  soundName: "EXILE_1",
  soundSetName: "EXILE_1",
  type: "fromEntity"
}];
var index = 0;
var PlaySound = false;
var text = "";
mp.events.add("playerCommand", _0x2bd11f => {
  if (is_admin !== true) {
    return;
  }
  if (_0x2bd11f.split(/[ ]+/).splice(0, 1)[0] === "sound") {
    PlaySound = !PlaySound;
    mp.game.graphics.notify(PlaySound ? "Soundviewer: ~g~activated" : "Soundviewer: ~r~deactivated");
  }
});
mp.keys.bind(37, true, function () {
  if (PlaySound) {
    if (index - 1 >= 0) {
      index--;
    } else {
      index = sounds.length - 1;
    }
    playSound();
  }
});
mp.keys.bind(39, true, function () {
  if (PlaySound) {
    if (index + 1 <= sounds.length) {
      index++;
    } else {
      index = 0;
    }
    playSound();
  }
});
let soundId = null;
function playSound() {
  sounds.forEach(async _0x1a0444 => {
    if (_0x1a0444.id === index) {
      if (_0x1a0444.type === "fromEntity") {
        if (soundId !== null) {
          mp.game.audio.stopSound(soundId);
          mp.game.audio.releaseSoundId(soundId);
        }
        await new Promise(_0x427cc1 => setTimeout(_0x427cc1, 100));
        soundId = mp.game.audio.getSoundId();
        mp.game.audio.playSoundFromEntity(soundId, _0x1a0444.soundName, localplayer.handle, _0x1a0444.soundSetName, true, 0);
      } else {
        mp.game.audio.playSoundFrontend(-1, _0x1a0444.soundName, _0x1a0444.soundSetName, true);
      }
      text = "Id: ~b~" + index + " ~w~SoundName: ~b~" + _0x1a0444.soundName + " ~w~SoundSetName: ~b~" + _0x1a0444.soundSetName;
    }
  });
}
mp.events.add("render", () => {
  if (PlaySound) {
    mp.game.graphics.drawText(text, [0.5, 0.9], {
      font: 0,
      color: [255, 255, 255, 185],
      scale: [0.4, 0.4],
      outline: true
    });
  }
});