module.exports = {
  MODULES_OBJECT_HASHES: MODULES_OBJECT_HASHES,
  MAIN_MODULE_OBJECT_HASH: MAIN_MODULE_OBJECT_HASH,
  MODULES_OBJECT_HASHES_MAX_HEALTH: MODULES_OBJECT_HASHES_MAX_HEALTH,
  MODULES_OBJECT_NAMES: MODULES_OBJECT_NAMES
};